### ISSUE TITLE
BioXAS Side and Main applications crash when trying to open scans

### ISSUE THREAD

**Issue by helfrij** [acquaman/acquaman#1589]
Originally, this issue was discovered when trying out the 'load data' capability of the energy calibration stuff in #1435, but appears to exist as well in master versions of BioXAS.

Both BioXAS Side and Main crash when trying to open scan data, either using the AMChooseScanDialog that's used in the energy calibration stuff, or just under 'Runs.' The gdb output seems to vary from crash to crash: sometimes pointing to AMCDFDataStore, sometimes MPlot, sometimes AMDataSourceSeriesData. Some crashes are accompanied by an error that 'BioXASXASScanConfiguration' isn't registered with the database (see note below), but others aren't (likely related to which scans in particular are opened, and in what database). Some gdb reports include a 'corrupted double-linked list', while others don't. 

A clean build of both MPlot and Acquaman doesn't seem to help.

Started with an empty database, running master BioXAS Side on my laptop. Did a scan, closed the open editor, and tried to open the same scan again--crashed when trying to open the scan. Tried again with Qt Debugger, the application did not crash (but didn't open the scan), did give an additional ErrorMon notice: "Could not find suitable plugin for loading the file format 'amCDFv1.'" Redirected the application to look for plugins in the correct folder ("File" > "Acquaman Settings"). Tried to open scan again, application crashed inside AMRawDataSource::axisValues() (line 190). The call here is for AMDataStore::axisValues().

I think the main problem is not likely related to the BioXAS database upgrade that's in the works, because the crashes persist in a clean master application build with a new, empty database that's isolated from the network synchronizer.

A clean build of MPlot and Acquaman this morning (Sept 8), and BioXASSide application can run scans and open the ones that were run, without issue. BioXAS Side on the Linux machines still doesn't open scans after clean build.

Things to try:
- ~~QDebugs in classes brought up by gdb output~~
- ~~clean build of MPlot and Acquaman~~
- ~~starting Acquaman with fresh test database. If successful, likely a database issue?~~
- ~~gdb output seems to indicate memory issue. Valgrind?~~

**Comment by helfrij** [comment]
Backtrace:

Program received signal SIGSEGV, Segmentation fault.
0x00000032c1a70e1e in _int_free () from /lib64/libc.so.6
(gdb) bt
#0  0x00000032c1a70e1e in _int_free () from /lib64/libc.so.6
#1  0x00000032c1a757ab in free () from /lib64/libc.so.6
#2  0x00002ae96d1a12c4 in AMCDFDataStore::axisValues (this=0xd7,
    axisId=<value optimized out>, axisStartIndex=<value optimized out>,
    axisEndIndex=<value optimized out>, outputValues=0x51efab0)
    at /home/beamline/tools/qt/qt-4.7.3-SL54-x86_64/include/QtCore/qvector.h:119
#3  0x000000000059b88b in AMRawDataSource::axisValues (this=0x4701570,
    axisNumber=0, startIndex=0, endIndex=214, outputValues=0x51efab0)
    at source/dataman/datasource/AMRawDataSource.cpp:190
#4  0x0000000000591df0 in AMDataSourceSeriesData::onAxisValuesChanged (
    this=0x509b4c0) at source/dataman/datasource/AMDataSourceSeriesData.cpp:178
#5  0x00000000005923e3 in AMDataSourceSeriesData::onSizeChanged (this=0x509b4c0)
    at source/dataman/datasource/AMDataSourceSeriesData.cpp:202
#6  0x0000000000592a1d in AMDataSourceSeriesData::setDataSource (this=0x509b4c0,
    dataSource=0x47015b0) at source/dataman/datasource/AMDataSourceSeriesData.cpp:71
#7  0x0000000000592f92 in AMDataSourceSeriesData (this=0x509b4c0,
    dataSource=0x47015b0, parent=<value optimized out>)
    at source/dataman/datasource/AMDataSourceSeriesData.cpp:38
#8  0x000000000054679c in AMScanViewInternal::createPlotItemForDataSource (
    this=0x4628560, dataSource=0x47015b0, plotSettings=@0x4507e10)
    at source/ui/dataman/AMScanView.cpp:735
#9  0x000000000054ee70 in AMScanViewMultiView::addScan (this=0x4628560, si=0)
    at source/ui/dataman/AMScanView.cpp:1226
#10 0x000000000054f9de in AMScanViewMultiView::onRowInserted (this=0x4628560,
    parent=<value optimized out>, start=0, end=0)
    at source/ui/dataman/AMScanView.cpp:1261
#11 0x00000000009f0eee in AMScanViewInternal::qt_metacall (this=0x4628560,
    _c=QMetaObject::InvokeMetaMethod, _id=13, _a=0x7fff86b3b200)
    at build_files/moc_AMScanView.cpp:224
#12 0x00000000009f13c5 in AMScanViewMultiView::qt_metacall (this=0x0,
    _c=QMetaObject::ReadProperty, _id=0, _a=0x51f0160)
    at build_files/moc_AMScanView.cpp:533
#13 0x00002ae9677f2d19 in QMetaObject::activate ()
   from /home/beamline/tools/qt/qt-4.7.3-SL54-x86_64/lib/libQtCore.so.4
#14 0x00002ae967844744 in QAbstractItemModel::rowsInserted ()
   from /home/beamline/tools/qt/qt-4.7.3-SL54-x86_64/lib/libQtCore.so.4
#15 0x00002ae9677d8387 in QAbstractItemModel::endInsertRows ()
   from /home/beamline/tools/qt/qt-4.7.3-SL54-x86_64/lib/libQtCore.so.4
#16 0x00000000005315b4 in AMScanSetModel::addScan (this=0x42e3790,

**Comment by helfrij** [comment]
The trace points back to AMCDFDataStore, but I think this may be an issue related to running BioXAS applications that straddle a database upgrade. The deployed applications do not have the upgrade yet, and so wouldn't be able to open BioXASXASScanConfigurations.

**Comment by helfrij** [comment]
Problem solved--applications were crashing because I wasn't building the appropriate plugins.
